#!/bin/bash

USERNAME=genom
RELEASE_VERSION=0.3.0
RELEASE=https://github.com/genom-project/genom/releases/download/${RELEASE_VERSION}/geth-linux-amd64
SYSTEMD_UNIT_FILE=/etc/systemd/system/genomnode.service
RPCPORT=8545
P2PPORT=30303
CACHE_SIZE=512
FROM_SCRATCH=n

function install_packages() {
    echo -e "\e[32mInstall necessary software\e[0m"
    apt-get -y -q install curl net-tools
}

function create_user() {
    getent passwd $USERNAME > /dev/null

    if [[ $? -eq 0 ]]; then
        remove_user
    fi

    echo -e "\e[32mCreate $USERNAME user\e[0m"
    useradd -m -G systemd-journal $USERNAME
}

function remove_user() {
    echo -e "\e[32mRemove user $USERNAME\e[0m"
    userdel -r $USERNAME 2> /dev/null
    if [[ $? -ne 0 ]]; then
        echo -e "\e[41mCan't delete genome user, maybe it's currently used\e[0m"
        exit 1
    fi
}

function node_info() {
    echo -e "\e[32mInstallation complete. MN registration data:\e[0m"

    enode=$(su - genom -c "/home/genom/geth attach --exec admin.nodeInfo.enode")

    echo "Enode ID: `echo ${enode%@*} | sed -e 's,\"enode://,,'`"
    echo "P2P Port: $P2PPORT"
    echo "RPC Port: $RPCPORT"
    echo "IP address: `curl -s ifconfig.co`"
}

function download_geth_release() {
    local release=$RELEASE

    echo -e "\e[32mDownload geth release $RELEASE\e[0m"

    case `arch` in
        "armv7l")
            release="${RELEASE%/*}/geth-linux-arm-7"
            ;;
    esac

    wget -q $release -O /home/genom/geth

    chown genom.genom /home/genom/geth

    chmod 755 /home/genom/geth
}

function check_rpc_port() {
    echo -e "\e[32mCheck if RPC port $RPCPORT is not used\e[0m"
    netstat -natup | grep LISTEN | grep $RPCPORT

    if [[ $? -eq 0 ]]; then
        echo -e "\e[41mRPC port $RPCPORT is used, specify another one using --rpcport parameter\e[0m"
        exit 1
    fi
}

function install_genom_service() {
    echo -e "\e[32mCreate systemd unit file $SYSTEMD_UNIT_FILE\e[0m"

    if [[ -f $SYSTEMD_UNIT_FILE ]]; then
        systemctl stop genomnode
        systemctl disable genomnode
        rm -f $SYSTEMD_UNIT_FILE
    fi

    cat > $SYSTEMD_UNIT_FILE << EOF
[Unit]
Description=Genom Node -- masternode service
After=network.target

[Service]
User=genom
Group=genom
Type=simple
Restart=always
RestartSec=30s
ExecStart=/home/genom/geth --hydra --rpc --rpcport $RPCPORT --cache=$CACHE_SIZE --atxi.autobuild --port $P2PPORT

[Install]
WantedBy=default.target
EOF

    echo -e "\e[32mEnable and start genomnode service\e[0m"

    systemctl daemon-reload
    systemctl enable genomnode
    systemctl start genomnode
}

function stop_node() {
    echo -e "\e[32mCheck previous masternode installation\e[0m"

    systemctl status genomnode --no-pager --full 2>/dev/null

    if [[ $? -eq 0 ]]; then
        echo -e "\e[33mMasternode is up, stop it\e[0m"
        systemctl stop genomnode
    fi
}

for i in "$@"; do
    case $i in
        --rpcport=*)
            RPCPORT="${i#*=}"
            shift
            ;;
        --p2pport=*)
            P2PPORT="${i#*=}"
            shift
            ;;
        --cache=*)
            CACHE_SIZE="${i#*=}"
            shift
            ;;
        --info)
            node_info
            exit 0
            shift
            ;;
        --upgrade)
            install_packages
            stop_node
            check_rpc_port
            download_geth_release
            install_genom_service
            exit 0
            shift
            ;;
        --from-scratch)
            FROM_SCRATCH=y
            shift
            ;;
        --help)
            echo "usage: mn-setup [options]"
            echo "    --upgrade          Upgrade geth version"
            echo "    --from-scratch     Install node from scratch"
            echo "    --rpcport=PORT     Specify custom RPC port for geth, 8545 is used by default"
            echo "    --p2pport=PORT     Specify custom P2P port for geth, 30303 is used by default"
            echo "    --cache=SIZE       Specify cache size for geth, 512Mb is used by default"
            echo "    --info             Show node parameters"
            exit 0
            shift
            ;;
    esac
done

if [[ $FROM_SCRATCH != "n" ]]; then

    read -p "All data will be removed. Are you sure? " -n 1 -r

    echo

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        install_packages

        stop_node

        check_rpc_port

        create_user

        download_geth_release

        install_genom_service

        journalctl --unit=genomnode | tail

        node_info
    fi
else
    echo "Nothing to do, please specify --upgrade or --from-scratch flag"
fi
